# Generated by Django 5.2.15 on 2026-06-25 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('duree_recolte_jours', models.PositiveIntegerField(help_text='Nombre de jours entre le semis et la récolte.', verbose_name='durée moyenne avant récolte (jours)')),
            ],
            options={
                'verbose_name': 'culture',
                'verbose_name_plural': 'cultures',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'type de sol',
                'verbose_name_plural': 'types de sol',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Exploitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('statut', models.CharField(choices=[('A_SEMER', 'Je vais semer'), ('DEJA_SEME', "J'ai déjà semé")], max_length=20, verbose_name='statut')),
                ('date_prevue_semis', models.DateField(blank=True, null=True, verbose_name='date prévue de semis')),
                ('date_reelle_semis', models.DateField(blank=True, null=True, verbose_name='date réelle de semis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exploitations', to='core.culture', verbose_name='culture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploitations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('type_sol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exploitations', to='core.typesol', verbose_name='type de sol')),
            ],
            options={
                'verbose_name': 'exploitation',
                'verbose_name_plural': 'exploitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.JSONField(help_text='Recommandations structurées produites par le moteur de décision.', verbose_name='résultat')),
                ('date_analyse', models.DateTimeField(auto_now_add=True, verbose_name="date d'analyse")),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.exploitation', verbose_name='exploitation')),
            ],
            options={
                'verbose_name': 'analyse',
                'verbose_name_plural': 'analyses',
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='FaoCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='Afrique centrale', help_text='Zone géographique couverte par ces données.', max_length=100, verbose_name='région')),
                ('mois_semis_debut', models.PositiveSmallIntegerField(help_text='Mois (1-12) du début de la période de semis.', verbose_name='mois début semis')),
                ('mois_semis_fin', models.PositiveSmallIntegerField(help_text='Mois (1-12) de fin de la période de semis.', verbose_name='mois fin semis')),
                ('mois_recolte_debut', models.PositiveSmallIntegerField(help_text='Mois (1-12) du début de la période de récolte.', verbose_name='mois début récolte')),
                ('mois_recolte_fin', models.PositiveSmallIntegerField(help_text='Mois (1-12) de fin de la période de récolte.', verbose_name='mois fin récolte')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendriers_fao', to='core.culture', verbose_name='culture')),
            ],
            options={
                'verbose_name': 'calendrier FAO',
                'verbose_name_plural': 'calendriers FAO',
                'ordering': ['culture__nom', 'region'],
            },
        ),
    ]
