# Generated by Django 5.2.15 on 2026-06-25 13:22

from django.db import migrations, models
import django.db.models.deletion


def clear_fake_fao_data(apps, schema_editor):
    """Supprime les calendriers FAO fictifs avant restructuration."""
    FaoCalendrier = apps.get_model('core', 'FaoCalendrier')
    FaoCalendrier.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_fake_fao_data, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='faocalendrier',
            options={
                'ordering': ['culture__nom', 'zone_aez', 'session_info'],
                'verbose_name': 'calendrier FAO',
                'verbose_name_plural': 'calendriers FAO',
            },
        ),
        migrations.AddField(
            model_name='culture',
            name='fao_crop_id',
            field=models.CharField(
                blank=True,
                help_text="Identifiant de la culture dans l'API FAO Crop Calendar.",
                max_length=10,
                null=True,
                unique=True,
                verbose_name='identifiant FAO',
            ),
        ),
        migrations.AddField(
            model_name='faocalendrier',
            name='fao_last_updated',
            field=models.CharField(blank=True, max_length=20, verbose_name='dernière mise à jour FAO'),
        ),
        migrations.AddField(
            model_name='faocalendrier',
            name='growing_period_jours',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name='période de croissance (jours)',
            ),
        ),
        migrations.AddField(
            model_name='faocalendrier',
            name='pays_code',
            field=models.CharField(
                default='CD',
                help_text='Code pays FAO (CD = République Démocratique du Congo).',
                max_length=3,
                verbose_name='code pays ISO',
            ),
        ),
        migrations.AddField(
            model_name='faocalendrier',
            name='session_info',
            field=models.CharField(
                blank=True,
                help_text='Ex. Saison A, Saison B.',
                max_length=100,
                verbose_name='saison / session',
            ),
        ),
        migrations.AddField(
            model_name='faocalendrier',
            name='zone_aez',
            field=models.CharField(
                default='Inconnue',
                help_text='Zone agro-écologique FAO (ex. Sud Ouest).',
                max_length=150,
                verbose_name='zone agro-écologique',
            ),
        ),
        migrations.AddField(
            model_name='faocalendrier',
            name='zone_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='identifiant zone FAO'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='duree_recolte_jours',
            field=models.PositiveIntegerField(
                default=90,
                help_text='Nombre de jours entre le semis et la récolte.',
                verbose_name='durée moyenne avant récolte (jours)',
            ),
        ),
        migrations.AlterField(
            model_name='culture',
            name='nom',
            field=models.CharField(max_length=150, unique=True, verbose_name='nom'),
        ),
        migrations.RemoveField(
            model_name='faocalendrier',
            name='region',
        ),
    ]
