# Generated by Django 5.2.15 on 2026-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_faocalendrier_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='faocalendrier',
            constraint=models.UniqueConstraint(
                fields=('culture', 'pays_code', 'zone_aez', 'session_info'),
                name='uniq_fao_calendrier_session',
            ),
        ),
    ]
