# Generated by Django 5.2.15 on 2026-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_faocalendrier_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='nom',
            field=models.CharField(max_length=150, verbose_name='nom'),
        ),
    ]
